[env]
WEB_ASSETS_SOURCE_PATH = { value = "ui/dist", relative = true }
WEB_ASSETS_TARBALL_PATH = { value = "ui/dist.tar", relative = true }
LIBSQLITE3_FLAGS = """-DSQLITE_ENABLE_COLUMN_METADATA=1 \
    -DSQLITE_THREADSAFE=2 \
    -DSQLITE_ENABLE_LOAD_EXTENSION=1 \
    -DSQLITE_ENABLE_FTS5=1 \
    -DSQLITE_ENABLE_DBSTAT_VTAB=1 \
    -DSQLITE_ENABLE_NULL_TRIM=1 \
    -DSQLITE_ENABLE_RTREE=1 \
    -DHAVE_READLINE=0 \
    -DGNU_SOURCE"""

[alias]
dev = "run -- --backend=memory --cors-allow-origin=http://localhost:8080 --cors-enabled=true"
lint = "clippy --all-targets --workspace"
embucket = "run -- --jwt-secret=test --backend=memory --cors-allow-origin=http://localhost:8080 --cors-enabled=true --tracing-level=debug"
embucket-trace = "run -- --jwt-secret=test --backend=memory --cors-allow-origin=http://localhost:8080 --cors-enabled=true --tracing-level=trace"
embucket-seed = "run -p embucket-seed -- --server-address 127.0.0.1:3000 --auth-user embucket --auth-password embucket --seed-variant typical"
update-functions = "run -p embucket-functions generate-implemented-functions"
e2e = "test --jobs 8 --workspace e2e_ -- --ignored"

# runs some of api-snowflake-rest tests sequentially with external server
test-rest = "test -p api-snowflake-rest --no-default-features --features external-server -- --test-threads 1"